### ISSUE TITLE
Searching not behaving as expected in adjustments

### ISSUE THREAD

**Issue by JohanWinther** [fsek/voting#231]
Substrings of names don't return the right person. If either the first name or last name is right, the person is returned but when both are correct, nothing is returned.
It's also possible to write the full name in either box and get the right person.

**Comment by davidwessman** [comment]
We are using [Textacular](https://github.com/textacular/textacular), the limits for matching are set in Postgres itself.

It would be great if you could write a failing test and submit it as a PR, with or without the fix.

**Comment by JohanWinther** [comment]
I'm sorry, I actually don't know Ruby and am not so experienced with unit tests in general. 
Maybe I can describe the problem below:

# Expected behaviours
1. **No input - all users**
![image](https://user-images.githubusercontent.com/28558941/34254651-45c8be02-e64d-11e7-81ef-62e76cf63310.png)

2. **Full first name - right user**
![image](https://user-images.githubusercontent.com/28558941/34254705-7f61ad0e-e64d-11e7-80cb-cbafb6844cbc.png)

# Unexpected behaviours
1. **Substring of name - no user**
![image](https://user-images.githubusercontent.com/28558941/34254690-6d4728ce-e64d-11e7-879f-f236f84d8258.png)

2. **Full first and last name - no user**
![image](https://user-images.githubusercontent.com/28558941/34254717-95b50eca-e64d-11e7-86dd-f102eb0d5518.png)

3. **Full name in first name - right user**
![image](https://user-images.githubusercontent.com/28558941/34254758-db7cc18c-e64d-11e7-96e3-ebf700a1459a.png)

4. **Last name in first name - right user**
![image](https://user-images.githubusercontent.com/28558941/34254782-fec7d21c-e64d-11e7-921b-546224d5449e.png)

And vice versa for the last name input box.

**Comment by davidwessman** [comment]
On the unexpected ones:

- [x] 1. This is the Postgres setting I think, the default is 30 % match. (I do get a match for your name on `Joh`)
- [x] 2. This was a bug that I could only reproduce on your name - so you will now be a test case :) 
- [ ] 3. Textacular is not working good on multiple words, perhaps we could look into doing some magic here - but then it would not work well for someone with a double name or whatever.
- [x] 4. This was because of the same bug as in 2.
