### ISSUE TITLE
Agenda: what to show for users

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#284]
![screen shot 2018-02-02 at 14 06 40](https://user-images.githubusercontent.com/6763624/35734709-563c31b4-0822-11e8-92bc-d3d4b8404bd0.png)

Right now we do not have any specific _content_ to show the users on the page for the Agenda.

What should we show them here?

- [ ] Current agenda (and which subitem)
- [ ] Documents to current agenda
- [ ] Current votes - in what way? Just a link? Pop up the form on the same page?

**Comment by JohanWinther** [comment]
Full agenda page
![image](https://user-images.githubusercontent.com/28558941/35861857-dda0cdc0-0b49-11e8-9bbc-fd749f3803c3.png)
The current agenda item (and possible subitem) should be shown at the top to make it easier for the user to keep up to speed.

Selected agenda item page
![image](https://user-images.githubusercontent.com/28558941/35862027-7c83e616-0b4a-11e8-8b27-92ef6408bc22.png)
It's a bit confusing that the current item is shown under all the other items. Maybe the current agenda item can be shown to the right of the main content instead (like in the image at the top)?

What is shown for *selected* agenda items:
- Documents to *selected* agenda item
- List of votings to *selected* agenda item
- Link to current agenda item (to the right)

What is shown for *current* agenda item:
- All of the above, but also the form for the voting associated with the *current* agenda item.

Does this sound reasonable? I think it would be much easier for the user if everything can be accessed from the Agenda rather than navigating to a separate menu with the Votings since all votings are attached to an agenda item anyways.

**Comment by davidwessman** [comment]
Gonna try to fix a proposal based on your ideas @JohanWinther  :+1:

**Comment by JohanWinther** [comment]
It would also probably be very good if only the votings for the currently selected subitems are shown.

See this example
![image](https://user-images.githubusercontent.com/28558941/35874335-857b78ca-0b6c-11e8-85c3-e147c1e4ee23.png)
Here we have three subitems with one voting for each. It is a bit confusing for the user that all the votings are shown. Probably better to only show when the subitem is selected.

**Comment by JohanWinther** [comment]
Also about the voting form. It would probably be good to keep the Votings tab and also show the voting form on the agenda item. Some people might want to only vote from the voting page while others like to roam the agenda and vote when it appears. This way both can be satisfied.

**Comment by davidwessman** [comment]
Closing this for now - will probably need to iterate more.
